### ISSUE TITLE
PR review and test before merge

### ISSUE THREAD

**Issue by AlexandreTedesco** [THP-Lab/rails-mock-api#11]

**Comment by AlexandreTedesco** [comment]
Le choix entre deux seeds est fonctionnel
La création de triple fonctionne et crée les atoms en conséquence mais la création de triplet imbriqué ne fonctionne pas.

**Comment by ZealRa** [comment]
Did several tests and you can create Atoms and Triples, but can't use an existing Triple to make a new one
